.ig
Copyright (C) 2022 Charles Michael Atkinson

Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\" No adjustment (ragged right)
.na
.TH wireguard_logger 8 "30 Mar 2023" "Auroville" "Version 1.0.2"
.SH NAME
wireguard_logger \- log active WireGuard clients to /var/log/wireguard.log
.SH SYNOPSIS
No arguments
.SH CONFIGURATION
No configuration
.SH DESCRIPTION
A script to log active WireGuard clients to /var/log/wireguard.log
.SH OPTIONS
No options
.SH EXIT STATUS
Always 0
.SH ENVIRONMENT
Environment variables are not used
.SH FILES
/etc/logrotate.d/wireguard-kit
.br
/var/log/wireguard.log
.SH BUGS
https://github.com/CharlesMAtkinson/wireguard-kit/issues
.SH AUTHORS
Charles Atkinson wireguard-kit@charlesmatkinson.org
.SH SEE ALSO
The wireguard-kit user guide, installed in /usr/share/doc/wireguard-kit
